project_id = "qsxoajvlubcoascenkqq"

[functions.send-contact-email]
verify_jwt = false

[functions.nhis-chat]
verify_jwt = false

[functions.get-mapbox-token]
verify_jwt = false

[functions.get-mapbox-directions]
verify_jwt = false

[functions.fetch-nhis-news]
verify_jwt = false

[functions.subscribe-news]
verify_jwt = false

[functions.confirm-news-subscription]
verify_jwt = false

[functions.unsubscribe-news]
verify_jwt = false
